version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: oupafamilly_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: oupafamilly

  backend:
    build: ./backend
    container_name: oupafamilly_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/oupafamilly
      - DB_NAME=oupafamilly
      - JWT_SECRET=your-jwt-secret-here
      - PORT=8001

  frontend:
    build: ./frontend
    container_name: oupafamilly_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001

volumes:
  mongodb_data:
